### ISSUE TITLE
Move svgs into Objects

### ISSUE THREAD

**Issue by komizutama** [openpantry/open_pantry#106]
Object format is the best way to link to svgs determine the correct way to do this and convert all svgs into these.

**Comment by fcapovilla** [comment]
I did a pull request to fix this issue, but I had to use img tags instead of object tags.
Object tags forced a rerender of SVG images on every modification, which means images flickered every time I added or removed an item in the cart.
This problems doesn't seem to occur when using img tags.

After doing some research, it seems that some browsers will not cache SVGs in object tag, so they're refetched and rerendered every time.

**Comment by fcapovilla** [comment]
The pull request was merged. Can we close this ticket?
