### ISSUE TITLE
Refactor gnarly Ecto query

### ISSUE THREAD

**Issue by bglusman** [openpantry/open_pantry#150]
I opened this discussion on Elixir forum months ago and nothing there competent sorted it out for me it has a blob of raw SQL that would vastly improve efficiency of a big query in the app, but never figured out a satisfactory solution other than maybe one or more SQL fragments.  Maybe there's an option other than group by, like a sub query or something?  Here's discussion and context: https://elixirforum.com/t/sql-vs-ecto-optimization-translation-help/5559

There's an accidentally checked in second version of the query called "play" that helps a little by executing just the query and not some subsequent Elixir data manipulation, so that may be useful for improving the performance.

**Comment by fcapovilla** [comment]
I gave this one a try because it seemed like an interesting challenge. :)
I used explicit joins in order to be able to select specific columns to reduce the amount of fetched data.
My dev environment doesn't have a lot of data right now, so I could not test the query in more complex situations, but it seemed to work and was 3 times faster than the previous query.

**Comment by bglusman** [comment]
Just responded over in the PR, thanks man!
